author:
  email: info@maisondemilune.ca
  name: Maison Demi Lune
baseurl: https://www.maisondemilune.ca
copyright: © Maison Demi Lune
languagecode: en-us
enablerobotstxt: true
relativeURLs: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
menu:
  main:
  - identifier: home
    name: Home
    weight: 10
    url: /
  - identifier: about
    name: About
    weight: 20
    url: /about/
  - identifier: booking
    name: Booking
    weight: 30
    url: /booking/
paginate: 50
social:
  envelope: mailto:info@maisondemilune.ca
  facebook: https://facebook.com/example
  instagram: https://instagram.com/example
theme: paige
title: Maison Demi Lune
titlecasestyle: Go
